### ISSUE TITLE
[issue] storybook setting

### ISSUE THREAD

**Issue by leehosu** [selabRepo/seBlog-Front-csr#1]
## Issue
- ui review를 위한 storybook install 및 setting

## checkList
- [x] cra setting
- [x] typeScript setting

**Comment by jeonyeonbin** [comment]
setting 관련된 내용 정리도 해주세요

**Comment by leehosu** [comment]
md 형식으로 정리해달라는건가용 ?

**Comment by jeonyeonbin** [comment]
md로 해도 되고 편하게 해주세요~
